name: CMake

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  pull_request_target:
    branches: ['main']
  workflow_dispatch:
    inputs:
      # run_all:
      #   description: 'Build all board configurations'
      #   required: true
      #   type: boolean
      #   default: true
      board_config:
        description: 'Build a specific board configuration'
        required: false
        type: choice
        options: &brd_cfgs
          # - ARCController
          # - ASiLVLABC
          # - ASiLVLWASD
          # - BentoBox
          # - Blank
          # - FlatboxRev4
          # - FlatboxRev5
          # - FlatboxRev5RGB
          # - FlatboxRev5Southpaw
          # - FlatboxRev5USBPassthrough
          # - FlatboxRev8
          # - Granola
          # - GranolaBeacon
          # - Haute42COSMOX
          - Haute42COSMOXC16S
          # - Haute42COSMOXMLite
          # - Haute42COSMOXMUltra
          # - Haute42COSMOXXAnalog
          # - KB2040
          # - KeyboardConverter
          # - Liatris
          # - MavercadeRev1
          # - MavercadeRev2
          # - MavercadeRev3
          # - MiSTercadeV2
          # - OpenCore0
          # - OpenCore0MIXUP
          # - OpenCore0WASD
          # - OSUMGP-RP2040
          # - Pico
          # - Pico2
          # - PicoAnn
          # - PicoFightingBoard
          # - PicoW
          # - PXPGamepad
          # - ReflexCtrlGenesis6
          # - ReflexCtrlNES
          # - ReflexCtrlSaturn
          # - ReflexCtrlSNES
          # - ReflexCtrlVB
          # - ReflexEncodeV1.2
          # - ReflexEncodeV2.0
          # - RP2040AdvancedBreakoutBoard
          # - RP2040AdvancedBreakoutBoardUSBPassthrough
          # - RP2040MiniBreakoutBoard
          # - RP2040MiniBreakoutBoardUSBPassthrough
          # - SeeedXIAORP2040
          # - SGFDevices
          # - SparkFunProMicro
          # - SparkFunProMicroRP2350
          # - Stress
          # - WaveshareZero
          # - ZeroRhythm

jobs:
  fsdata:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: www/package-lock.json

      - run: npm ci
        working-directory: ${{ github.workspace }}/www

      - run: npm run build --if-present
        working-directory: ${{ github.workspace }}/www
        env:
          CI: 'false'

      - name: Upload fsdata
        uses: actions/upload-artifact@v4
        with:
          name: fsdata
          path: ${{ github.workspace }}/lib/httpd/fsdata.c
          if-no-files-found: error

  release:
    needs: [fsdata]

    strategy:
      # fail-fast: false
      fail-fast: true
      matrix:
        board_config: *brd_cfgs
        os:
          - ubuntu-22.04
          # - macos-latest
          # - windows-latest

    runs-on: ${{ matrix.os }}

    env:
      BUILD_TYPE: Release
      GP2040_BOARDCONFIG: ${{ matrix.board_config }}

    steps:
      ## Begin Global Setup ##

      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/checkout@v6
        with:
          repository: raspberrypi/pico-sdk
          ref: 2.1.1
          path: pico-sdk
          submodules: true

      - uses: actions/download-artifact@v5
        with:
          name: fsdata
          path: ${{ github.workspace }}/lib/httpd/

      - uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.19.x"

      - uses: carlosperate/arm-none-eabi-gcc-action@v1.11.1

      ## End Global Setup ##

      - name: Pico Build Configure CMake
        shell: bash
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        env:
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
          SKIP_WEBBUILD: 'TRUE'

      - name: Pico Build
        shell: bash
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel $(nproc)

      - name: Upload Pico Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GP2040-CE - ${{ matrix.board_config }}
          path: ${{ github.workspace }}/build/GP2040-CE_*_${{ matrix.board_config }}.uf2
          if-no-files-found: error

      - name: Upload Pico ELF Artifact
        if: ${{ matrix.board_config == 'Pico' }}
        uses: actions/upload-artifact@v4
        with:
          name: GP2040-CE - ${{ matrix.board_config }} - ELF
          path: ${{ github.workspace }}/build/GP2040-CE_*_${{ matrix.board_config }}.elf
          if-no-files-found: error
