name: Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  pull_request_target:
    branches: ['main']
  workflow_dispatch:
  workflow_call:

jobs:
  fsdata:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: www/package-lock.json

      - run: npm ci
        working-directory: ${{github.workspace}}/www

      - name: Build WWW
        working-directory: ${{github.workspace}}/www
        run: npm run build --if-present
        env:
          CI: 'false'

      - name: Upload fsdata
        uses: actions/upload-artifact@v4
        with:
          name: fsdata
          path: ${{github.workspace}}/lib/httpd/fsdata.c
          if-no-files-found: error

  release:
    runs-on: ubuntu-22.04

    needs: [fsdata]

    strategy:
      matrix:
        GP2040_BOARDCONFIG: ['Haute42COSMOXMUltra']

    env:
      BUILD_TYPE: Release
      GP2040_BOARDCONFIG: ${{matrix.GP2040_BOARDCONFIG}}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - uses: actions/checkout@v6
        with:
          repository: raspberrypi/pico-sdk
          ref: 2.1.1
          path: pico-sdk
          submodules: true

      - name: Download fsdata
        uses: actions/download-artifact@v5
        with:
          name: fsdata
          path: ${{github.workspace}}/lib/httpd

      - uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.19.x'

      - uses: carlosperate/arm-none-eabi-gcc-action@v1.11.1

      - name: Pico Build Configure CMake
        shell: bash
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        env:
          PICO_SDK_PATH: ${{github.workspace}}/pico-sdk
          SKIP_WEBBUILD: 'TRUE'

      - name: Pico Build
        shell: bash
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(nproc)

      - name: Upload Pico Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GP2040-CE - ${{ matrix.GP2040_BOARDCONFIG }}
          path: ${{github.workspace}}/build/GP2040-CE_*_${{ matrix.GP2040_BOARDCONFIG }}.uf2
          if-no-files-found: error
